### PR TITLE
Implement the first available version

### PR DESCRIPTION
**Pull request by loonghao**
@mottosso Please have a look, this MR just Implement the first available version and this currently only supports Windows yet.

### CODE REVIEW

**Comment by mottosso** [comment]
Wow, this is fantastic, great work. :D There's a README, with install instructions and a gif showcasing how it works and what it looks like. I could not have asked for more.

@tokejepsen Look! Are you able to take this for a spin? :)

@loonghao May I ask if you are using this yourself and if so, for what kind of projects?

**Comment by loonghao** [comment]
@mottosso 
I am going to use it in film or game projects.
As far as I know, if we don’t use Shotgun toolkit and Ftrack connect, it is difficult for small studios to integrate Photoshop with existing 3D pipelines.
pyblish is a very mature framework. Using [photoshop-python-api](https://github.com/loonghao/photoshop-python-ap) and pyblish can easily help those studios that do not use Shotgun or Ftrack to integrate pipelines.

**Comment by mottosso** [comment]
Oh you're also the author of the Photoshop API, that is amazing. Warm welcome to Pyblish. :) I'll add maintainer permissions for you to this repository so you can work freely.

You're probably up to speed already, but for completeness there has been minor usage of Photoshop and Pyblish in the past, most recently a conversation last year [on the forums](https://forums.pyblish.com/t/pyblish-for-photoshop/99/6). An integration such as this should make this much easier.

**Comment by loonghao** [comment]
@mottosso This is great, Thank you.

I am about to join a game company. I will try to see if there is a chance to push that to use `pyblish` in them. I hope I can contribute more code to the community in the future.

**Comment by davidlatwe** [comment]
Nice work @loonghao !

**Comment by loonghao** [comment]
> Nice work @loonghao !

Thank you!

**Comment by tokejepsen** [comment]
Tagging in the Pype team as well, cause there is already a Photoshop implementation there and I know they are working on a cross OS re-implementation.
@mkolar

**Comment by mottosso** [comment]
For completeness, @mkolar is working on a separate project that builds on Pyblish called Avalon, for which there is a separate Photoshop integration. @tokejepsen Is it [this one here](https://github.com/getavalon/core/pull/524/files#diff-d6afd6a4fca182e9f45e60d495cf82b3)?

Would this be an opportunity to bridge the Pyblish-related aspects of the two? Is there anything from Pype/Avalon that is suitable for Pyblish standalone? From a quick glance, it appears to be a separate COM exposure to Python than the one @loonghao has provided here.

**Comment by loonghao** [comment]
For pyblish-photoshop, the current infrastructure can be used in windows.

Since `pyblish` itself allows the loading of plugins to be defined by the environment, I think it is possible to write plugins in any way in the future.

About this [MR](https://github.com/getavalon/core/pull/524/files#diff-d6afd6a4fca182e9f45e60d495cf82b3),
That core functions still use COM exposure to python, the extension of Photoshop just helps us create buttons in Photoshop.

if just for create buttons in photoshop, I think we can use [jsx](https://github.com/pyblish/pyblish-photoshop/pull/1/files#diff-49956e1d95aa51e66ccc0e197a9cc22cR52) to call python and use Qt to write a shelf tool may be more convenient for us to use and configure.

**Comment by tokejepsen** [comment]
Think this a great initial version!

When implementing the Avalon implementation I actually came across pyps but opted to not rely on external libraries.

I've not got access to Photoshop anymore, so cant test this but happy to merge for other people to test.

**Comment by loonghao** [comment]
merged.

**Comment by mottosso** [comment]
Went ahead and made if official! :)

- https://forums.pyblish.com/t/pyblish-for-photoshop/99/7

**Pull request merged**
